name: tier_lists_api
description: The interface and models for an API providing access to tier lists.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.0
  json_annotation: ^4.6.0
  meta: ^1.7.0
  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  test: ^1.21.4