name: http_tier_lists_api
description: A Flutter implementation of the TierListsAPI that uses remote storage.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.4
  http: ^1.4.0
  tier_lists_api:
    path: ../tier_lists_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0