name: local_storage_tier_lists_api
description: A Flutter implementation of the TierListsAPI that uses local storage.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.8.0
  rxdart: ^0.28.0
  shared_preferences: ^2.0.0
  tier_lists_api:
    path: ../tier_lists_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0