name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no root@134.199.200.50 << 'EOF'
            set -e

            echo "Changing to project directory..."
            cd /var/www/html/COP4331-LargeProject

            echo "Pulling latest code..."
            git reset --hard HEAD
            git pull origin main

            echo "Installing backend dependencies..."
            cd backend
            npm install

            echo "Restarting or starting pm2 processes..."
            pm2 restart backend || pm2 start server.js --name backend
            pm2 restart server || pm2 start server.js --name server

            echo "Building frontend..."
            cd ../frontend
            npm install
            npm run build

            echo "Deployment complete!"
          EOF
