name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no root@134.199.200.50 << EOF
            set -e

            echo "Loading environment..."
            export NVM_DIR="\$HOME/.nvm"
            [ -s "\$NVM_DIR/nvm.sh" ] && \. "\$NVM_DIR/nvm.sh"
            [ -s "\$NVM_DIR/bash_completion" ] && \. "\$NVM_DIR/bash_completion"

            echo "Navigating to project..."
            cd /var/www/html/COP4331-LargeProject

            echo "Resetting any local changes..."
            git reset --hard HEAD
            echo "Pulling latest code from origin..."
            git pull origin main

            echo "Installing backend dependencies..."
            cd backend
            npm install

            echo "Restarting backend server with PM2..."
            pm2 restart server || pm2 start server.js --name server

            echo "Building frontend..."
            cd ../frontend
            npm install
            npm run build

            echo "Deployment complete!"
          EOF
